### PR TITLE
Revert changes to ProcessConfig and add docs

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by ali-abrar** [comment]
Looks like the readme doesn't build anymore

**Review by ali-abrar — APPROVED** [review]

**Comment by Ericson2314** [comment]
I wonder if we should have so level functions like `Handle -> Event t something -> IO ()` and `Handle -> IO (Event t something)` that users with more exotic pipes/processes can use.

**Comment by 3noch** [comment]
I think the goal is to not be a general purpose "handles" library but focus hard on processes. Exotic uses cases are out of scope.

**Comment by ali-abrar** [comment]
I agree. I’d like to see some specific use cases or encounters with
limitations before we expand to cover them.

**Pull request merged**
