### PR TITLE
WIP: Try switching to github actions and testing more compilers

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by Ericson2314** [comment]
Whad’ya know, non-Nix just failing arbitrarily.

**Review by tomsmalley — APPROVED** [review]
Hmm is that macos timing out? I'll set off a build on my mac, but this looks good to me

**Comment by tomsmalley** [comment]
This built under 8.10.5 on macOS for me.

**Comment by Ericson2314** [comment]
Yeah I'll just merge this.

**Pull request merged**
